version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: meow
      POSTGRES_PASSWORD: meow
      POSTGRES_DB: cryptomai_db
    volumes:
      - postgres_data:/var/lib/postgresql@16/data
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit.log
      - RABBITMQ_SASL_LOGS=/var/log/rabbitmq/rabbit-sasl.log
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3


volumes:
  postgres_data:
  rabbitmq_data:
    driver: local
  rabbitmq_logs:
    driver: local